# Generated by Django 2.2.5 on 2021-01-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mentors',
            field=models.BooleanField(default=False),
        ),
    ]
