# Generated by Django 2.2.5 on 2021-05-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='now_user_point',
        ),
    ]
