# Generated by Django 2.2.5 on 2021-04-05 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210323_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('time_paid', models.DateTimeField()),
                ('time_refund', models.DateTimeField()),
                ('state', models.CharField(choices=[('Use', '사용'), ('Pending', '보류중'), ('Cancled', '취소'), ('Accrual', '적립'), ('Withdraw', '인출')], max_length=40)),
                ('value_paid', models.IntegerField(default=0)),
                ('value_refund', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Point_Record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
