# Generated by Django 2.2.5 on 2021-05-26 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210526_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
