# Generated by Django 2.2.5 on 2021-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='time_paid',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='value_paid',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='point',
            name='time_refund',
        ),
        migrations.RemoveField(
            model_name='point',
            name='value_refund',
        ),
        migrations.AlterField(
            model_name='point',
            name='state',
            field=models.CharField(choices=[('사용', '사용'), ('보류중', '보류중'), ('취소', '취소'), ('적립', '적립'), ('인출', '인출')], max_length=40),
        ),
    ]
