# Generated by Django 2.2.5 on 2021-04-07 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='now_user_point',
            field=models.ForeignKey(db_column='point', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Point_Record_now_point', to=settings.AUTH_USER_MODEL),
        ),
    ]
