# Generated by Django 2.2.5 on 2021-03-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210320_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='where',
        ),
        migrations.CreateModel(
            name='BookedTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time', models.DateField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation')),
            ],
            options={
                'verbose_name': 'Booked Time',
                'verbose_name_plural': 'Booked Times',
            },
        ),
    ]
